/** CodeMirror mode values and labels for the editor sidebar. */
export const LANGUAGE_OPTIONS = [
  { value: "clike", label: "C / C++ / C# / Java" },
  { value: "css", label: "CSS" },
  { value: "dart", label: "Dart" },
  { value: "django", label: "Django" },
  { value: "dockerfile", label: "Dockerfile" },
  { value: "go", label: "Go" },
  { value: "htmlmixed", label: "HTML (mixed)" },
  { value: "javascript", label: "JavaScript" },
  { value: "jsx", label: "JSX" },
  { value: "markdown", label: "Markdown" },
  { value: "php", label: "PHP" },
  { value: "python", label: "Python" },
  { value: "r", label: "R" },
  { value: "rust", label: "Rust" },
  { value: "ruby", label: "Ruby" },
  { value: "sass", label: "Sass" },
  { value: "shell", label: "Shell" },
  { value: "sql", label: "SQL" },
  { value: "swift", label: "Swift" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" },
];

/** CodeMirror theme names for the theme selector. */
export const THEME_OPTIONS = [
  { value: "default", label: "Default" },
  { value: "3024-day", label: "3024 Day" },
  { value: "3024-night", label: "3024 Night" },
  { value: "abbott", label: "Abbott" },
  { value: "abcdef", label: "Abcdef" },
  { value: "ambiance", label: "Ambiance" },
  { value: "ayu-dark", label: "Ayu Dark" },
  { value: "ayu-mirage", label: "Ayu Mirage" },
  { value: "base16-dark", label: "Base16 Dark" },
  { value: "base16-light", label: "Base16 Light" },
  { value: "bespin", label: "Bespin" },
  { value: "blackboard", label: "Blackboard" },
  { value: "cobalt", label: "Cobalt" },
  { value: "colorforth", label: "Colorforth" },
  { value: "darcula", label: "Darcula" },
  { value: "duotone-dark", label: "Duotone Dark" },
  { value: "duotone-light", label: "Duotone Light" },
  { value: "eclipse", label: "Eclipse" },
  { value: "elegant", label: "Elegant" },
  { value: "erlang-dark", label: "Erlang Dark" },
  { value: "gruvbox-dark", label: "Gruvbox Dark" },
  { value: "hopscotch", label: "Hopscotch" },
  { value: "icecoder", label: "Icecoder" },
  { value: "idea", label: "IDEA" },
  { value: "isotope", label: "Isotope" },
  { value: "juejin", label: "Juejin" },
  { value: "lesser-dark", label: "Lesser Dark" },
  { value: "liquibyte", label: "Liquibyte" },
  { value: "lucario", label: "Lucario" },
  { value: "material", label: "Material" },
  { value: "material-darker", label: "Material Darker" },
  { value: "material-palenight", label: "Material Palenight" },
  { value: "material-ocean", label: "Material Ocean" },
  { value: "mbo", label: "Mbo" },
  { value: "mdn-like", label: "MDN-like" },
  { value: "midnight", label: "Midnight" },
  { value: "monokai", label: "Monokai" },
  { value: "moxer", label: "Moxer" },
  { value: "neat", label: "Neat" },
  { value: "neo", label: "Neo" },
  { value: "night", label: "Night" },
  { value: "nord", label: "Nord" },
  { value: "oceanic-next", label: "Oceanic Next" },
  { value: "panda-syntax", label: "Panda Syntax" },
  { value: "paraiso-dark", label: "Paraiso Dark" },
  { value: "paraiso-light", label: "Paraiso Light" },
  { value: "pastel-on-dark", label: "Pastel on Dark" },
  { value: "railscasts", label: "Railscasts" },
  { value: "rubyblue", label: "Rubyblue" },
  { value: "seti", label: "Seti" },
  { value: "shadowfox", label: "Shadowfox" },
  { value: "solarized", label: "Solarized" },
  { value: "the-matrix", label: "The Matrix" },
  { value: "tomorrow-night-bright", label: "Tomorrow Night Bright" },
  { value: "tomorrow-night-eighties", label: "Tomorrow Night Eighties" },
  { value: "ttcn", label: "TTCN" },
  { value: "twilight", label: "Twilight" },
  { value: "vibrant-ink", label: "Vibrant Ink" },
  { value: "xq-dark", label: "XQ Dark" },
  { value: "xq-light", label: "XQ Light" },
  { value: "yeti", label: "Yeti" },
  { value: "yonce", label: "Yonce" },
  { value: "zenburn", label: "Zenburn" },
];
